### ISSUE TITLE
Line No. 409 in DateField.class.php is crashing the PHP/Apache Server (Reports Menu)

### ISSUE THREAD

**Issue by lavanyadeepak** [anuko/timetracker#110]
Line No. 409 in DateField.class.php is crashing the PHP/Apache Server (Reports Menu) with the error

PHP Fatal error:  Uncaught Error: Undefined constant "DIR_NAME" in C:\\LavanyaDeepak\\Personal\\timetracker\\WEB-INF\\lib\\form\\DateField.class.php:409\nStack trace:\n#0 C:\\LavanyaDeepak\\Personal\\timetracker\\WEB-INF\\lib\\form\\DateField.class.php(409): constant('DIR_NAME')\n#1 C:\\LavanyaDeepak\\Personal\\timetracker\\WEB-INF\\lib\\form\\FormElement.class.php(101): DateField->getHtml()\n#2 C:\\LavanyaDeepak\\Personal\\timetracker\\WEB-INF\\lib\\form\\Form.class.php(207): FormElement->toArray()\n#3 C:\\LavanyaDeepak\\Personal\\timetracker\\reports.php(504): Form->toArray()\n#4 {main}\n  thrown in C:\\LavanyaDeepak\\Personal\\timetracker\\WEB-INF\\lib\\form\\DateField.class.php on line 409, referer: http://localhost:8099/timetracker/time.php

Workaround/Solution for this is:

In config.php, line 37 which appears commented from OEM should be uncommented:

define('DIR_NAME', 'timetracker');

**Comment by anuko** [comment]
The issue is addressesd in version 1.19.28.5535.
