### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by zidingz** [anuko/timetracker#114]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by anuko** [comment]
Hello,

The instructions for reporting security issues are in CONTRIBUTING.md.

Basically, either use the contact form at 
https://www.anuko.com/contact.htm or email the details directly to me at 
***@***.***

Hope it helps,

Nik

**Comment by zidingz** [comment]
Thank you! I'll send you over the details shortly. Much appreciated!

**Comment by anuko** [comment]
Hello. Which version of Time Tracker the original submitter was testing with? The CSRF issue was fixed long ago, see https://www.anuko.com/time-tracker/news/cross-site-request-forgery-vulnerability.htm

Am I missing something? Did you actually test the issue with oor latest code at all?

**Comment by zidingz** [comment]
Hi, the researcher has confirmed that he conducted his tests on `https://timetracker.anuko.com`, so I assume it's the latest code?

If you encounter issues accessing the report links we sent you, kindly let me know so I can lend some assistance. Thanks!

**Comment by anuko** [comment]
I could not reproduce the problem yesterday t using the html provided. I created a test login csrf_test for you at https://timetracker.anuko.com to see if the attack actually works. Let me know.

Also, please fix your system and remove our account from huntr.dev as it sends way too many useless, unwanted notifications, which is especially annoying if this vulnerability report is bogus. And currently I cannot see anything there.

**Comment by zidingz** [comment]
Hi @anuko, we're so sorry for this unpleasant experience, and will immediately stop these notifications coming to you. Thank you for being so patient and forthcoming with us, and I hope we can deliver more substance in future.
