### ISSUE TITLE
[BUG] Incorrect visualization in Reports with disabled projects

### ISSUE THREAD

**Issue by xBounceIT** [anuko/timetracker#118]
## Steps to reproduce

1. Enable plugin Clients
2. Create 2 projects 'test1' and 'test2'
3. Create a test client 'ClientTest'
4. Assign the 2 projects to the Client
5. Check if in Reports, choosing client 'ClientTest', the projects assigned are both visible.
6. Go in Projects, edit 'test1' and disable it.
7. Go back to Report, choose the client 'ClientTest' and check the projects available. You should have 'test2' and a blank space, instead of both the projects assigned.

Example image
![immagine](https://user-images.githubusercontent.com/35002896/156201859-1e2dc022-a0db-41b0-8f13-550ab33bc080.png)

**Comment by anuko** [comment]
Thanks for this bug report. I fixed the issue in TT version 1.20.1.5647. A reference to a project should now be removed from all clients when you are making a project inactive.
