### ISSUE TITLE
[Feature Request] Flag to let disable projects be available in the Reports page

### ISSUE THREAD

**Issue by xBounceIT** [anuko/timetracker#120]
A use case would be to make a yearly summary with all the projects for a client.

As of now the disabled projects are not available in the Reports page, which is kinda inconvenient. A single flag to allow the disabled projects to make reports would be useful.

**Comment by anuko** [comment]
It's already available. See https://www.anuko.com/time-tracker/what-is/inactive-projects-display-option.htm

**Comment by xBounceIT** [comment]
Missed that, got it thanks.
Il 3 mar 2022, 12:39 +0100, anuko ***@***.***>, ha scritto:
