### ISSUE TITLE
[HELP]Can't find php.ini while trying to expand the upload file size

### ISSUE THREAD

**Issue by TikokitoTikal** [anuko/timetracker#124]
I'm trying to update my time tracker,
from this doc https://www.anuko.com/time-tracker/install-guide/upgrade.htm at ```start with old data```
it says:

```php
$form->addInput(array('type'=>'upload','name'=>'xmlfile','value'=>'browse','maxsize'=>16777216)); // 16 MB file upload limit.
// Note: for the above limit to work make sure to set upload_max_filesize and post_max_size in php.ini to at least 16M.
```

I'm trying to find where is the php.ini file in the directory/ or maybe where is it defined to change but there is nothing....
I don't have it and even not the repository.

what am I missing?

**Comment by anuko** [comment]
php.ini is not a part of Time Tracker, it is a part of your php install. To learn where your current file is located, you can create a file, for example named test.php with the following content: `<?php phpinfo(); ?>` and then execute it in the browser (by pointing your browser to test.php file located where you place it.

You can override the values in php.ini in your .htaccess file. Among other things, you will probably need to increase max_execution_time, too if your export is too large.

Hope it helps.
