### ISSUE TITLE
Updating User cause Fatal Error (500) - Javascript handleClientRole issue on user_edit.php

### ISSUE THREAD

**Issue by hroma** [anuko/timetracker#128]
Hi, 
On user_edit.php, I get the following console error;
```
Uncaught TypeError: Cannot read properties of null (reading 'value')
at handleClientRole (user_edit.php?id=2:127:55)
at onload (user_edit.php?id=2:22:98)
```
Seems that the issue come from
Line 62 of user_edit.tpl:
`var selectedRoleId = document.getElementById("role").value;`
Line 281 of user_edit.php
`$smarty->assign('onload', 'onLoad="document.userForm.name.focus();handleClientRole();"');`

**Steps to reproduce:**
1) Menu->Users
2) Edit an existing user (console is showing a warning on edit_user.php)
3) Try to modify a value and hit save button

**Result:**
500 Internal Server Error

**Comment by hroma** [comment]
**Temporary fix: replaced on line 154 /user_edit.php:**

```diff
-      <td class="text-cell">{$user->role_name} {if $can_swap}<a href="swap_roles.php">{$i18n.form.user_edit.swap_roles}</a>{/if}</td>
+      <td class="text-cell">{$user->role_name}**<input type="hidden" id="role" name="role" value="{$user->id}">** {if $can_swap}<a href="swap_roles.php">{$i18n.form.user_edit.swap_roles}</a>{/if}</td>
```
What it fix: 
1) onPageLoad: javascript looking for missing id=role.value / causing console error
2) PageSubmit: form require $user->id to update corresponding user

Could someone check if there is more elegant way to do it and/or to create a pull request ?

**Comment by hroma** [comment]
**Temporary fix: replaced on line 154 /user_edit.php:**

```diff
-      <td class="text-cell">{$user->role_name} {if $can_swap}<a href="swap_roles.php">{$i18n.form.user_edit.swap_roles}</a>{/if}</td>
+      <td class="text-cell">{$user->role_name}**<input type="hidden" id="role" name="role" value="{$user->id}">** {if $can_swap}<a href="swap_roles.php">{$i18n.form.user_edit.swap_roles}</a>{/if}</td>
```
What it fix: 
1) onPageLoad: javascript looking for missing id=role.value / causing console error
2) PageSubmit: form require $user->id to update corresponding user

Could someone check if there is more elegant way to do it and/or to create a pull request ?

**Comment by anuko** [comment]
Which version of Time Tracker are you using? The mentioned line numbers do not seem to match the latest,

**Comment by hroma** [comment]
I'm using version 3.7.
Sorry, the changes proposed are located inside /WEB-INF/templates/user_edit.tpl called by /user_edit.php

**Comment by anuko** [comment]
> I'm using version 3.7. Sorry, the changes proposed are located inside /WEB-INF/templates/user_edit.tpl called by /user_edit.php

Version 3.7 of Time Tracker code does not exist. The most recent is 1.21.9.5724 and is displayed in the footer. In recent code it is taken from initialize.php, line 15:

`define("APP_VERSION", "1.21.9.5724");

In older versions it was defined in WEB-INF/templates/footer.tpl

I recommend re-testing the problem with the most recent code to make sure it still exists and not solved long ago.

**Comment by hroma** [comment]
Why did I take the version found in docker-compose.yml??  Mystery...
I was using 1.21.6.5719. Just updated to 1.21.9.5724.
Problem persist and can be replicated as mentioned above (hope it helps).

**Comment by anuko** [comment]
I addressed a JavaScript error on user_edit.tpl when role control is not available.

I don't know why a JavaScript error in client browser results in you seeing 500 Internal Server Error - probably something is wrong with your browser setup, apparently you will see other issues related to client script errors. Perhaps try using another browser?
