### ISSUE TITLE
[BUG] Unable to set hours on Monday while using Weekly view

### ISSUE THREAD

**Issue by xBounceIT** [anuko/timetracker#131]
Version: 1.22.16.5801

Steps to reproduce:

1. Select weekly view
2. Set time for monday
3. Submit

The hour will not be set and in the logs this will appear:

Undefined array key 5 in /var/www/html/timetracker/WEB-INF/lib/ttWeekViewHelper.class.php on line 183, referer: /week.php
PHP Warning:  Undefined array key 5 in /var/www/html/timetracker/WEB-INF/lib/ttWeekViewHelper.class.php on line 184, referer: /week.php
Undefined array key 5 in /var/www/html/timetracker/WEB-INF/lib/ttWeekViewHelper.class.php on line 198, referer: /week.php
Undefined array key 5 in /var/www/html/timetracker/WEB-INF/lib/ttWeekViewHelper.class.php on line 199, referer: /week.php
Undefined array key 5 in /var/www/html/timetracker/WEB-INF/lib/ttWeekViewHelper.class.php on line 230, referer: /week.php
Undefined array key 5 in /var/www/html/timetracker/WEB-INF/lib/ttWeekViewHelper.class.php on line 231, referer: /week.php
Undefined array key 5 in /var/www/html/timetracker/WEB-INF/lib/ttWeekViewHelper.class.php on line 246, referer: /week.php
Undefined array key 5 in /var/www/html/timetracker/WEB-INF/lib/ttWeekViewHelper.class.php on line 247, referer: /week.php
Undefined array key 19 in /var/www/html/timetracker/week.php on line 468, referer: /week.php
PHP Warning:  Trying to access array offset on value of type null in /var/www/html/timetracker/week.php on line 468, referer: /week.php
PHP Warning:  Undefined array key 19 in /var/www/html/timetracker/week.php on line 543, referer: /week.php
PHP Warning:  Trying to access array offset on value of type null in /var/www/html/timetracker/week.php on line 543, referer: /week.php
PHP Warning:  Undefined array key 5 in /var/www/html/timetracker/WEB-INF/lib/ttWeekViewHelper.class.php on line 183, referer: /week.php
PHP Warning:  Undefined array key 5 in /var/www/html/timetracker/WEB-INF/lib/ttWeekViewHelper.class.php on line 184, referer: /week.php
PHP Warning:  Undefined array key 5 in /var/www/html/timetracker/WEB-INF/lib/ttWeekViewHelper.class.php on line 198, referer: /week.php
 Warning:  Undefined array key 5 in /var/www/html/timetracker/WEB-INF/lib/ttWeekViewHelper.class.php on line 199, referer: /week.php
 Warning:  Undefined array key 5 in /var/www/html/timetracker/WEB-INF/lib/ttWeekViewHelper.class.php on line 230, referer: /week.php
 Warning:  Undefined array key 5 in /var/www/html/timetracker/WEB-INF/lib/ttWeekViewHelper.class.php on line 231, referer: /week.php
 Warning:  Undefined array key 5 in /var/www/html/timetracker/WEB-INF/lib/ttWeekViewHelper.class.php on line 246, referer: /week.php
 Warning:  Undefined array key 5 in /var/www/html/timetracker/WEB-INF/lib/ttWeekViewHelper.class.php on line 247, referer: /week.php
 Warning:  Trying to access array offset on value of type null in /var/www/html/timetracker/week.php on line 227, referer: /week.php
 Warning:  Trying to access array offset on value of type null in /var/www/html/timetracker/week.php on line 242, referer: /week.php
 Warning:  Undefined array key 5 in /var/www/html/timetracker/week.php on line 231, referer: /week.php
 Warning:  Trying to access array offset on value of type null in /var/www/html/timetracker/week.php on line 227, referer: /week.php
 Warning:  Trying to access array offset on value of type null in /var/www/html/timetracker/week.php on line 244, referer: /week.php
 Warning:  Trying to access array offset on value of type null in /var/www/html/timetracker/week.php on line 245, referer: /week.php
 Warning:  Undefined array key 5 in /var/www/html/timetracker/week.php on line 231, referer: /week.php
 Warning:  Undefined array key 5 in /var/www/html/timetracker/week.php on line 231, referer: /week.php
 Warning:  Undefined array key 5 in /var/www/html/timetracker/week.php on line 231, referer: /week.php

**Comment by anuko** [comment]
Please try the latest version, as there were some fixes to Week view since 1.22.16.5801. See change log at https://www.anuko.com/time-tracker/change-log/index.htm

If the problem can be reproduced on https://timetracker.anuko.com please provide steps to see it. Thanks.

**Comment by xBounceIT** [comment]
I've tried v1.22.17.5804 in testing but it still seems to not be working.

**Comment by anuko** [comment]
Can you try to reproduce the problem at https://timetracker.anuko.com/ and provide steps to it as my testing so far is not showing it. I also do not see any errors in the provided log.

**Comment by xBounceIT** [comment]
I managed to replicate it on the online demo:

1. Set the first weekday as Monday (When this was set as default to Sunday it was working)
2. Try to put hours through week view on Monday

It should be empty.

**Comment by anuko** [comment]
Thanks for clarifying the problem. I now confirm that with the first day of week set to Monday, I also see it. will look into this.

**Comment by xBounceIT** [comment]
Hi,

following internal testing i can confirm that with v1.22.18.5805 the issue has been resolved.

Glad to help and thanks for the quick patch!

Regards,
Daniel D.
