### ISSUE TITLE
[BUG] Favorite reports missing when selecting another user as a manager / top manager

### ISSUE THREAD

**Issue by xBounceIT** [anuko/timetracker#133]
Tested on the demo online v1.22.19.5806

### Requirements

- Have two or more users
- Have a favorite report saved for the main user

### Steps to reproduce

1. From time, select the user with the favorite report saved
2. Go to reports and check if the favorite report is appearing
3. Go back to Time and select another user
4. Go back to Reports, the favorite report will be missing

Favorite report visible when select main user:
![immagine](https://github.com/anuko/timetracker/assets/35002896/633b3296-d938-45ad-a09b-718a07bb7613)

Favorite report missing when selecting different user:
![immagine](https://github.com/anuko/timetracker/assets/35002896/356bb7ac-647a-4265-b19e-6495ac03f068)

**Comment by anuko** [comment]
Favorite reports are, in the current design, are associated with a specific user. If you change the user on behalf of whom you are currently working, you will not see fav reports for another user.

**Comment by xBounceIT** [comment]
So it is expected behaviour, i guess?

**Comment by anuko** [comment]
Yes, it is.
