### ISSUE TITLE
Some mobile pages are not centered on screen

### ISSUE THREAD

**Issue by anuko** [anuko/timetracker#17]
The following mobile pages are not centered horizontally on mobile screen.

time_edit.php
task_edit.php
project_edit.php
login.php

White space is left on the right. The effect is worse in landscape orientation of the phone.

![mobile_page_not_centered](https://cloud.githubusercontent.com/assets/2672997/18691385/cf1b9f68-7f82-11e6-8ae6-94dbe71201c1.png)

**Comment by HJvD123** [comment]
Hi, is there any way for me to help on this issue? I don't have any programming skills, but I could help testing any improvement.
