### ISSUE TITLE
Suggestion: Custom fields for user profiles

### ISSUE THREAD

**Issue by Adevade** [anuko/timetracker#19]
This would be good for adding a _Social Security Number/Personal Identity Number_ or any useful information, such as an address, phone numbers, etc. 

Maybe you, as manager, could decide per custom field if it should be publicly visible to everyone logged in or private to just the managers?

**Comment by anuko** [comment]
This sounds like a good idea to me. I think anything security-sensitive should be either available to managers only, or configurable who can see it. Therefore, design of the feature requires very careful thinking.

**Comment by Adevade** [comment]
Have you given any more thought to this idea?

**Comment by anuko** [comment]
If we do it, perhaps provide a switch for managers to turn it off / on (for users who do not need the feature), together with uncompleted entry status merged in PR#20. Does it make sense?
