### ISSUE TITLE
cron.php fetching wrong table ID

### ISSUE THREAD

**Issue by mrbaozi** [anuko/timetracker#35]
Hi, first of all thanks so much for making this tool :)

**System:**
mysql  Ver 14.14 Distrib 5.7.19, for Linux (x86_64) using  EditLine wrapper
PHP 7.0.18-0ubuntu0.16.04.1

**Issue:**
In cron.php, line 50:
```
 $sql = "select * from tt_cron c
   left join tt_fav_reports fr on (c.report_id = fr.id)
   where $now >= c.next and fr.status = 1
   and c.status = 1 and c.report_id is not null and c.email is not null";
```
This code replaces the tt_cron.id with tt_fav_reports.id, which leads to line 94 not updating the correct entry for $next:
```
  $sql = "update tt_cron set last = $now, next = $next where id = ".$val['id'];
```
A quick fix that I've tested is replacing line 50 with the following:
```
 $sql = "select * from tt_fav_reports fr
   left join tt_cron c on (c.report_id = fr.id)
   where $now >= c.next and fr.status = 1
   and c.status = 1 and c.report_id is not null and c.email is not null";
```
This keeps all columns but uses tt_cron.id instead of tt_fav_reports.id.
If you'd like I can open a PR.

**Comment by anuko** [comment]
Thanks for finding the issue and providing a fix. I refactored this query for clarity in the latest code.
