### ISSUE TITLE
Change mktime() to time()

### ISSUE THREAD

**Issue by mrbaozi** [anuko/timetracker#36]
In cron.php line 48, consider replacing the call to mktime() with time(), because:

> Note:
As of PHP 5.1, when called with no arguments, mktime() throws an E_STRICT notice: use the time() function instead.

I noticed it after getting messages from cron-daemon because of non-zero exit status. Simple drop-in replacement fixes the issue, both functions return the same timestamp when called with no arguments.

**Comment by anuko** [comment]
Thanks. Replaced.
