### ISSUE TITLE
phpinfo.php leaks potentially sensitive information

### ISSUE THREAD

**Issue by michaelshmitty** [anuko/timetracker#37]
The severeness of this issue is debatable.
Still, I was surprised to come across the phpinfo.php file in my production installation of Anuko. Perhaps it's better to remove this file from the project?
It would seem to only serve for debugging purposes.
Your production installation also reveals this information: https://timetracker.anuko.com/phpinfo.php
It could potentially help malicious attackers to gain more information about your system easily.

Anuko is great software. Many thanks for writing and maintaining it!

**Comment by anuko** [comment]
I removed the file. Thanks.
