### ISSUE TITLE
How to keep time tracker TTL persistent?

### ISSUE THREAD

**Issue by molochmike** [anuko/timetracker#39]
Hi,

There is this configuration below.  I have uncomment out the last line to allow the session to prolong persistent up to 24 hours.  But when the user logon and use, they were timed out within less than 1 hour.  Is there any other way to make the TTL session persistent?

Thanks.

**Time to live in seconds for script session cookie (named tt_PHPSESSID).
// PHPSESSID_TTL
//
// Lifetime in seconds for tt_PHPSESSID cookie. Time to live is extended by this value
// with each visit to the site so that users don't have to re-login. 
// define('PHPSESSID_TTL', 86400);**

**Comment by anuko** [comment]
Persistent forever? No. I recommend increasing the value to something that works reasonably well for your users.

**Comment by molochmike** [comment]
Hi Anuko,

My meaning of persistent does not refer 'forever'.  I do not think you answer my question properly.  The value of "86400" in seconds is 24 hours as defined in your existing "config.php".  The problem now is upon user has login, it timed out after 30 minutes!

**Comment by anuko** [comment]
See http://php.net/manual/en/session.configuration.php#ini.session.gc-maxlifetime, specifically, "    Note: If different scripts have different values of session.gc_maxlifetime but share the same place for storing the session data then the script with the minimum value will be cleaning the data. In this case, use this directive together with session.save_path." - This could be your issue.

**Comment by anuko** [comment]
I added PHP_SESSION_PATH define in config.php in Time Tracker version 1.12.3.3684 to avoid garbage collection interference from other scripts. Please try using it to see if it helps.

**Comment by molochmike** [comment]
@anuko 

It is working now after I change the setting for php parameter "session.gc_maxlifetime" from 1440 to 86400 and restart apache.

Thanks for the help.
