### ISSUE TITLE
Fix quota and allow decimal input for work weeks with uneven working hours

### ISSUE THREAD

**Issue by dtmichel** [anuko/timetracker#47]
Currently it is only possible to insert montly quotas with integer values. In some countries this does not work as the working hours are not always integer values.

To make quota work in version 1.13.11.3737 it is necessary to modify line 97 in quotas.php as follows:
$monthsData = $quota->get($selectedYear, **_null_**);

Otherwise PHP (at least >=7.x) throws an error that only one parameter was given instead of two. In Apache this leads to an HTTP Error 500.

**Comment by anuko** [comment]
I fixed the missing parameter issue to address PHP 7.x error this commit https://github.com/anuko/timetracker/commit/98f86b438c91861eed8d384a7e9ab27e97d7d8b7

As per non-integer monthly quotas -do you have a fix or I am missing something?

**Comment by dtmichel** [comment]
Thanks for fixing the Error 500!

The other issue/problem can be fixed by modifying the length and style attributes of the form input in quotas.php:
`$form->addInput(array('type'=>'text','name'=>$name,'maxlength'=>**_6_**,'value'=> $value,'style'=>'width:**_75_**px'));`

In the database table `tt_monthly_quotas` the column `quota ` needs to be of the type decimal(5,2).

**Comment by anuko** [comment]
Unfortunately, the proposed fix to input look and database field type change would not work, or should I say would not work properly for all users. There are users with comma as a decimal mark, the fix presents them with a dot. There is still no validation of entered parameters, which is required. I would further assume that most users probably have integer quotas - therefore by displaying not properly localized controls with decimal .00 we are not doing an improvement here, although we do provide a fix for one special case. I think we need a better fix that takes case of all these issues.

**Comment by dtmichel** [comment]
This should not be a major issue. When displaying the quotas on the page it would be sufficient to use localization features. When updating quotas it is necessary to replace commas with dots, as numbers are not localized in the dbms.

**Comment by dtmichel** [comment]
This should not be a major issue. When displaying the quotas on the page it would be sufficient to use localization features. When updating quotas it is necessary to replace commas with dots, as numbers are not localized in the dbms.

**Comment by dtmichel** [comment]
This should not be a major issue. When displaying the quotas on the page it would be sufficient to use localization features. When updating quotas it is necessary to replace commas with dots, as numbers are not localized in the dbms.

**Comment by dtmichel** [comment]
This should not be a major issue. When displaying the quotas on the page it would be sufficient to use localization features. When updating quotas it is necessary to replace commas with dots, as  are not localized in the dbms.

**Comment by anuko** [comment]
This problem is now addressed in Time Tracker version 1.17.8.3801. I see a similar problem with integer value for day work hours. There are also usability issues for the monthly quota configuration page and a need for code refactoring. We'll deal with them separately. Unless bugs are found, this specific problem is fixed.

**Comment by anuko** [comment]
Quotas plugin may be redesigned soon, along with other things, See this topic about [new Quotas plugin features](https://www.anuko.com/forum/viewtopic.php?f=4&t=1997). You are welcome to comment on the forum.

**Comment by anuko** [comment]
Reopening. to collect further user feedback for redesign work.

**Comment by anuko** [comment]
Closing, as nothing is happening here. Quota plugin was improved with a couple of things, though, a couple of months back.

1) "Balance" output was added to display. It is an accumulated quota from the 1st of the month. Whether or not this is an improvement is questionable though, as this clutters the screen, and not all would want to see balance with quotas, also translating this compactly is a challenge. This may need further work.

2) Quota percent property was added to users,. It establishes user share of quota between 0-100%. For example, a part-time employee may be at 50% of quota.
