### ISSUE TITLE
Reports.php performance problem

### ISSUE THREAD

**Issue by cbbThor** [anuko/timetracker#5]
Softwareversion: 1.7.8.3094

to open the reports.php document a co-manager needs about 35-40 seconds. We suspect the following code in "reports.php":

```
$user_list = array();
if ($user->canManageTeam() || $user->isClient()) {
  // Prepare user and assigned projects arrays.
  $users = ttTeamHelper::getActiveUsers();
  foreach ($users as $single_user) {
    $user_list[$single_user['id']] = $single_user['name'];
    $projects = ttProjectHelper::getAssignedProjects($single_user['id']);
    if ($projects) {
      foreach ($projects as $single_project) {
        $assigned_projects[$single_user['id']][] = $single_project['id'];
      }
    }
  }
  $row_count = ceil(count($user_list)/3);
  $form->addInput(array('type'=>'checkboxgroup',
    'name'=>'users',
    'data'=>$user_list,
    'layout'=>'V',
    'groupin'=>$row_count,
    'style'=>'width: 100%;'
  ));
}
```

in this sample a co-manager requests about 50 users and 800 projects.
is there a patch or any solutions/ suggestions to improve the performance?

thanks in advance!

**Comment by anuko** [comment]
I can try to profile the problem if you share a db with us (remove sensitive data, we just need to see the issue), or reproduce it at https://timetracker.anuko.com. If you want to investigate further with a db copy please contact me via anuko.com website.

**Comment by cbbThor** [comment]
We found the Problem in some array_intersect() Funktions. These were implemented by us and without those the performance is perfect.
Thank you!
