### ISSUE TITLE
[Suggestion] more team options

### ISSUE THREAD

**Issue by bonnedav** [anuko/timetracker#53]
I think that READONLY_START_FINISH, FUTURE_ENTRIES, ALLOW_OVERLAP, SHOW_HOLIDAYS, and COST_ON_REPORTS should be per team not global. I also think that there should be a (non-default) global option to restrict changing team options and plugins to managers only and not co-managers.

**Comment by dalers** [comment]
IMHO, I think this is part of a bigger “what’s in a profile”, “what’s in a project”, why can’t a project have local tasks as well as global tasks, etc., discussion. 

 

I think there’s a significant opportunity for a timesheet system in “Postmodern ERP”, which IIUC means assembling a system as needed for a specific situation. A member of the ERPNext community told me he’s built systems with the “core” implemented using ERPNext, SuiteCRM, Apache ODE a workflow engine, an erlang-based bpe, and even Drupal workflows as the primary driver. TT is a fantastic tool (especially with what Week View has become), but my point is that a review of what is global, what is a project, what is a task, etc. might also drive adoption for TT as the best timesheet system to integrate with in a larger system  (well, LDAP authentication is integration, but I’m also curious if any go beyond authentication and manage or the process data somehow).

 

Cheers,

Dale

**Comment by anuko** [comment]
> READONLY_START_FINISH, FUTURE_ENTRIES, ALLOW_OVERLAP, SHOW_HOLIDAYS, and COST_ON_REPORTS should be per team not global.

I agree. This will require redoing of how team settings are stored perhaps with a round of rethinking of what the plugins are and how to "plug" them in properly.

> I also think that there should be a (non-default) global option to restrict changing team options and plugins to managers only and not co-managers.

It makes sense, More user roles are needed together with a flexible mechanism to assign rights to roles and users to roles. This will require a significant re-write, too.

**Comment by bonnedav** [comment]
You already have a pseudo permission system internally. You can expand on and optimise it to cover more actions. Then change roles to be dynamic and stored a per team array and read perms from that. Though that will probably require a rewrite of the team setting storage system as well.

**Comment by anuko** [comment]
I made READONLY_START_FINISH, FUTURE_ENTRIES, ALLOW_OVERLAP, SHOW_HOLIDAYS teem-configurable. I am unsure about COST_ON_REPORTS - is it needed at all? I am thinking about removing the choice altogether from the global settings and always provide it, as you can disable it on reports.php and not display the column. I forgot what was the original intention for the global setting, perhaps to keep the reports.php page simple, and perhaps for situations when cost is not even in the scope of time tracking.

**Comment by bonnedav** [comment]
I do not think that a global option is necessary. Just have a check box on reports.php that will show/hide the column for that report. that way it can be per report. Maybe have a similar thing for other columns as well, to customize reports?

**Comment by anuko** [comment]
I removed COST_ON_REPORTS global setting and its handler for now. If the thing turns out as needed later on, we can redo it as a per-team option, perhaps as a part of some advanced team settings page.

I'll start to look at user rights to see what can be done. It may take a while, as people wanted some radical changes to roles, including a supervisor role to manage multiple teams / groups.

**Comment by bonnedav** [comment]
I think the first thing to do about rights and roles is to change all instances of canManageTeam with explicit right checks. That way we have more flexibility to assign more actions to different rights later on.

Also I have some other ideas as well. Maybe you should open an issue for suggestions to help keep track of then all.
________________________________

**Comment by anuko** [comment]
I introduced MANAGER_ONLY_TEAM_SETTINGS define in config.php as a temporary workaround for this issue, until proper role editor is done, which may take a long time if we want to accommodate multiple units / groups per organization, and this requires a lot of thinking before coding.

**Comment by bonnedav** [comment]
That will work for now thank you. My thought was for now to add a new role that is like Co manager but can't change settings. And then allow Co manager to change some settings but not all. I want to try to do is in a PR but I just had to take my laptop in to get fixed and all I have is my phone. I think you should open a new issue for ideas and discussion about rights and roles.

**Comment by anuko** [comment]
>  I think you should open a new issue for ideas and discussion about rights and roles.

I opened a thread about roles and permissions redesign [here](https://www.anuko.com/forum/viewtopic.php?f=4&t=1833)

Feel free to provide input.

**Comment by anuko** [comment]
Closing as all issues are now resolved and user rights redesign discussion is moved into a separate issue #55, and on the product support forum [here](https://www.anuko.com/forum/viewtopic.php?f=4&t=1833).
