### ISSUE TITLE
Replace i18n_holidays per year with calendar ics or similar

### ISSUE THREAD

**Issue by eschaettin** [anuko/timetracker#65]
Is it possible to use any other (external) resource as calendar for holidays instead of changing i18n_holidays per year

**Comment by anuko** [comment]
Holidays implementation needs to be re-designed and re-coded to handle holidays better. We welcome contributors who would like to improve this feature.

**Comment by eschaettin** [comment]
Probably an idea for the implementation could be to store an ICS-File or URL with public holidays per team/group (or other) an parse it to the current i18n_holidays array

**Comment by anuko** [comment]
Closing as the holidays are now configurable on group level, see https://www.anuko.com/time_tracker/faq/holidays.htm
