### ISSUE TITLE
Issues when importing XML file

### ISSUE THREAD

**Issue by fwolfst** [anuko/timetracker#67]
Importing a XML file in version 1.17.98.4319 (on Ubuntu 18.04, apache, PHP 7.2.10-0ubuntu0.18.04.1) fails with two errors/warnings in apaches error logs and a white page in the browser. I guess the first is a relatively simple php-compatibility thing:

`PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/timetracker/WEB-INF/lib/pear/MDB2.php on line 826, referer: http://xxx/timetracker/import.php`

The other one looks more problematic to me:

`PHP Fatal error:  Uncaught Error: Call to undefined function xml_parser_create() in /var/www/timetracker/WEB-INF/lib/ttImportHelper.class.php:393\nStack trace:\n#0 /var/www/timetracker/import.php(47): ttImportHelper->importXml()\n#1 {main}\n  thrown in /var/www/timetracker/WEB-INF/lib/ttImportHelper.class.php on line 393, referer: http://xxx/timetracker/import.php`

But maybe its just a missing package? I installed via the installation instructions.

PS: The contribution page does not clearly state whether there is a prefered platform for issues (github "vs." forum). I'd prefer github, so I post this issue here. Please guide me to the better place if there is one.

**Comment by fwolfst** [comment]
Indeed missing packages wrt the second message. I guess the installation instructions at https://www.anuko.com/time_tracker/install_guide/linux_quick_install.htm should be updated 
```sh
$ php -m | grep xml
libxml
```

For ubuntu-users the solution is to install `php-xml`:
```sh
$ sudo apt install php-xml
```

I still get errors in the frontend ("XML error: Mismatched tag at line 28", ...) but these might come from version differences (ex- and importing systems run different timetracker-versions) or encoding issues. I'll investigate and open another issue if I do not find an explanation or solution.

**Comment by fwolfst** [comment]
I dont know PHP, but afaiu, the first warning should be silenced by changing

`if (!count($dsn)) {`
to something like
`if (strlen($dsn) == 0) {`

According to http://php.net/manual/en/function.strlen.php PHP Versions 5.3+ handle the input to `strlen` consistently (`strlen(null) == strlen('')`, that is what is needed I think).

I will create a github pull request if you like.

**Comment by anuko** [comment]
> I still get errors in the frontend ("XML error: Mismatched tag at line 28", ...) 

Are you importing a group? Is your XML file valid? What exactly is on line 28 and which tag is mismatched?

**Comment by anuko** [comment]
> I dont know PHP, but afaiu, the first warning should be silenced by changing
> 
> `if (!count($dsn)) {`
> to something like
> `if (strlen($dsn) == 0) {`
> 
> According to http://php.net/manual/en/function.strlen.php PHP Versions 5.3+ handle the input to `strlen` consistently (`strlen(null) == strlen('')`, that is what is needed I think).
> 
> I will create a github pull request if you like.

If this is related to WEB-INF/lib/pear/MDB2.php file, then it is a part of the existing PEAR package, we should not be updating it here, but if a new package exists with this issue fixed we can replace the entire thing.

**Comment by fwolfst** [comment]
> > I still get errors in the frontend ("XML error: Mismatched tag at line 28", ...)
> 
> Are you importing a group? Is your XML file valid? What exactly is on line 28 and which tag is mismatched?

The file was broken, that problem is solved. Yes, its about a group import (we need this as long as the subgroup-feature is not yet there).

**Comment by fwolfst** [comment]
> If this is related to WEB-INF/lib/pear/MDB2.php file, then it is a part of the existing PEAR package, we should not be updating it here, but if a new package exists with this issue fixed we can replace the entire thing.

I believe it is. MDB2 looks relatively dead (https://github.com/pear/MDB2)

**Comment by anuko** [comment]
Closing because libxml is enabled by default in PHP, so the error should not be seen unless someone specifically compiled PHP without libxml. Additionally, I added this check in dbinstall.php:

`// Check is libxml is enabled (which is a PHP default).
if (!function_exists('libxml_clear_errors')) {
  echo('<font color="red">Error: libxml is not enabled. It is required for import group operation (to parse XML).</font><br>');
}`

So, in a rare case of disabled libxml, users should be able to see info about it. As for PHP warnings, import-export was recently re-done as part of subgroup work, so that one may no longer be relevant, but there are other places in code that generate warnings, something to be aware of and fix eventually.

If you would like to help with addressing specific warnings please provide some more details - where they appear, suggested fix, etc.

Thanks!
