### ISSUE TITLE
Add ability for project managers to validate reported times

### ISSUE THREAD

**Issue by antirais** [anuko/timetracker#70]
Validating and checking reported tasks helps project managers to assure that all reported hours are valid. There should be a checkbox for each reported task / time and calendar should visually show days that contain records that are not validated. Also, there should be a check or a warning, when user tries to generate report that contains not validated records.

**Comment by anuko** [comment]
Timesheet approval is something that needs to be done properly, perhaps with an associated workflow, and perhaps integrated with a week view. See Week view plugin.

**Comment by antirais** [comment]
Didn't find the source in the timetracker plugins folder. Please provide a link to Week view plugin source code and documentation.

**Comment by anuko** [comment]
I created 2 separate plugins.

1. Report approval - allows manager to approve report items. This works for both time log and expenses. Some info about it is [here](https://www.anuko.com/time_tracker/what_is/report_approval.htm). This plugin does not have email workflow.

2. Timesheets - allows users to associate time log entries into a timesheet, and submit it for approval. Managers can either approve or disapprove. This one comes with email workflow. I don't have much documentation on this one, just a [forum post](https://www.anuko.com/forum/viewtopic.php?t=2008) for now. Will try to improve later on this.

**Comment by anuko** [comment]
Closing as the feature is implemented in Report Approval plugin.
