### ISSUE TITLE
Enable grouping by custom fields in Reports forms

### ISSUE THREAD

**Issue by harmscon** [anuko/timetracker#79]
Hello,
It would be very useful to enable Group by custom fields in the reports.php form. 
Our example case is:
Client: xyz
Project: Support
Task: Support Ticket
Ticket Number: A1234     <--- this is our custom text field. Grouping by this field would be very useful to show who and how long each ticket takes to resolve.

**Comment by anuko** [comment]
Closing, as grouping by custom fields in reports was implemented long ago.
