### ISSUE TITLE
Consider expanding mobile page access

### ISSUE THREAD

**Issue by thurt** [anuko/timetracker#8]
Hello--

My manager account would really like to have access to more pages on mobile. The release version I installed on my server initially only allowed access to the time entry form from mobile.

Have you considered expanding mobile page access?  And would you be interested in PR's for this? Thanks

**Comment by anuko** [comment]
Sounds like a good idea, as other users also expressed a need to access more pages on mobiles. I suggest going in small iterations, as refactoring will most likely be required to accommodate this change.

**Comment by thurt** [comment]
Hi anuko,

Thanks for getting back to me. I would be happy to start looking at putting
together a PR for this.

I have already made a few pages mobile accessible on my deployed app
(projects, clients, users) with a few css tweaks to the template files from
the regular pages.

The main table had a fixed width 720 px. Removing that width helped prevent
horizontal page scrolling on mobile. However, the new/edit pages still have
horizontal scroll on mobile due to fixed width input tags.

I'm not familiar with third party PHP tooling/plugins though. It looks like
time tracker uses a few such plugins for db access and forms? Can you
explain those quickly and how they are integrated with time tracker?

**Comment by anuko** [comment]
For presentation, Time Tracker uses Smarty template engine, see http://www.smarty.net/about_smarty

It is included in WEB-INF/lib/smarty folder.

For a page, we normally have a .php file and a corresponding .tpl file (which is responsible for presentation). In a PHP file, we assign variables for s Smarty template to use, then call it to display things, something like this:

$smarty->assign('img_file_name', $img_ref);
$smarty->assign('chart_selector', $chart_selector);
$smarty->assign('forms', array($chart_form->getName() => $chart_form->toArray()));
$smarty->assign('title', $i18n->getKey('title.charts'));
$smarty->assign('content_page_name', 'charts.tpl');
$smarty->display('index.tpl');

Hope it helps.

**Comment by thurt** [comment]
Thanks that helps get me started.

I'm wondering about the best way to go about a dev install. ie. Do you recommend going through the regular [setup process](https://www.anuko.com/time_tracker/install_guide/linux_quick_install.htm) for a development install? It looks like `config.php` would be the only thing I should avoid commiting right?

Also have you considered using a php test framework?

**Comment by thurt** [comment]
Looks like `config.php` is already in `.gitignore`! I now have a dev setup based on the repo files.
 
Is there version information somewhere in this repo? As I mentioned, I've already done some edits on my deployed app and I was going to start moving those modified files over to my dev install. But I don't know how to determine differences between this repo and the release version from the website.

**Comment by anuko** [comment]
Look at WEB-INF/templates/footer.tpl for version info. It is displayed on most pages in the footer.

**Comment by anuko** [comment]
I merged your pull request #9. Just noticed a problem on the Users page for Inactive users (the Inactive Users table displays with a Delete column, compared to with just Edit for the Active Users table).

It would probably make sense to remove the Edit column too, in order to reduce presentation issues. Perhaps by making the edit feature by a click on a link in the Login column.


![mobile_inactive_users_issue](https://cloud.githubusercontent.com/assets/2672997/18013273/dbfaddbe-6bac-11e6-9b2c-67f39662dc83.png)

**Comment by thurt** [comment]
> Perhaps by making the edit feature by a click on a link in the Login column.

Yea good idea. I haven't gotten to that yet. 

Also be aware that I haven't yet added the Delete button into the edit pages. You are welcome to add that if you have time but I was going to do that sometime this weekend!

**Comment by anuko** [comment]
There are some alignment issues in the currently merged code that need fixing. See https://github.com/anuko/timetracker/issues/17
