### ISSUE TITLE
Show custom fields in Time and Week forms

### ISSUE THREAD

**Issue by harmscon** [anuko/timetracker#80]
There are list of times shown at the bottom of the time.php and week.php. It would be great to also show the custom fields in that list.

**Comment by danklee19** [comment]
Have a look to:
https://www.anuko.com/forum/viewtopic.php?f=4&t=1748
and
https://www.anuko.com/forum/viewtopic.php?f=4&t=2045

Two lines and Two files only :-)

Database (ttTimeHelper.class.php) query is already changed in latest version.

**Comment by anuko** [comment]
Closing, as support for this was implemented long ago with a display option (Group - Display options - Configure) called "Custom fields" that defines whether or not to display the fields.
