### ISSUE TITLE
error

### ISSUE THREAD

**Issue by deepthi2514** [anuko/timetracker#85]
WEB-INF/config.php file does not exist. its showing this error

**Comment by anuko** [comment]
> WEB-INF/config.php file does not exist.

You need to create one by copying it from config.php.dist and modifying DSN and other values as needed.

**Comment by deepthi2514** [comment]
I'm not getting you

**Comment by naidu** [comment]
@deepthi2514 there is a template file `WEB-INF/config.php.dist`.  This file needs to be copied as `WEB-INF/config.php` and make necessary changes before starting the app.  Hope this helps?
