### ISSUE TITLE
Suggestion: Custom fields for projects

### ISSUE THREAD

**Issue by eschaettin** [anuko/timetracker#86]
Is it possible to add custom fields to project? (not only for time and user)

**Comment by ram-fabian-heinrich** [comment]
Custom fields have been added last year:
 - https://github.com/anuko/timetracker/commit/00a75a7ed04fa22de4211891580deee454f04ec2
 - https://www.anuko.com/time-tracker/what-is/entity-type.htm

**Comment by anuko** [comment]
Closing, as custom fields for projects are already implemented.
