### ISSUE TITLE
Sessions time out early

### ISSUE THREAD

**Issue by TimothyAlexisVass** [anuko/timetracker#89]
Sessions kept timing out early.
I found this post on the forum:
https://www.anuko.com/forum/posting.php?mode=reply&f=4&t=2059

If someone has a forum account, you could add the following correction in that post.
Please add it to the master branch too.

After enabling the lines WEB-INF/config.php that was supposed to fix it, I was unable to log in, just as described in that forum post.

So I made the following correction in initialize.php (lines 84-91):
$phpsessid_ttl = defined('PHPSESSID_TTL') ? PHPSESSID_TTL : 60*60*24;
// Set lifetime for garbage collection.
ini_set('session.gc_maxlifetime', $phpsessid_ttl);
// Set PHP session path, if defined to avoid garbage collection interference from other scripts.
if (defined('PHP_SESSION_PATH')) {
  ini_set('session.save_path', **realpath(PHP_SESSION_PATH)**);
  ini_set('session.gc_probability', 1);
}

The original code was corrected by enclosing PHP_SESSION_PATH in realpath()

**Comment by anuko** [comment]
Code fixed in TT 1.19.16.5189.
