### ISSUE TITLE
Trying to load chart does not work

### ISSUE THREAD

**Issue by naidu** [anuko/timetracker#94]
I tried to use the chart but it fails with error HTTP ERROR 500.  The server log shows below

`anuko-timetracker | [Fri Jun 19 11:50:56.693582 2020] [php7:error] [pid 20] [client 192.168.2.20:48420] PHP Fatal error:  Uncaught Error: Call to undefined function imageftbbox() in /var/www/html/WEB-INF/lib/libchart/classes/view/text/Text.php:67\nStack trace:\n#0 /var/www/html/WEB-INF/lib/libchart/classes/view/chart/PieChart.php(210): Text->printText(Resource id #65, 148.98288271018, 274.99908917797, Object(Color), '50%', '/var/www/html/W...', 18)\n#1 /var/www/html/WEB-INF/lib/libchart/classes/view/chart/PieChart.php(239): PieChart->drawPercent()\n#2 /var/www/html/WEB-INF/lib/PieChartEx.class.php(38): PieChart->printPie()\n#3 /var/www/html/charts.php(219): PieChartEx->renderEx(Array)\n#4 {main}\n  thrown in /var/www/html/WEB-INF/lib/libchart/classes/view/text/Text.php on line 67, referer: https://localhost/time.php`

**Comment by anuko** [comment]
Closing after merging a pull request #95.
